### ISSUE TITLE
[Feature Request] Failing mode for CI

### ISSUE THREAD

**Issue by Jubeki** [enlightn/enlightn#1]
**Is your feature request related to a problem? Please describe.**
I'd like to run enlightn in the CI to check every time if there are problems occurring. Currently the CI passes even if there are problems.

**Describe the solution you'd like**
It would be nice if there is a flag (something like --fail) that the status code returned is not "okay" and the CI will fail this step.
Some Analyzers could probably be ignored (depends on the use case) so I would also suggest an config entry where you can add Analyzers which will show errors but will not mark the analytics as failed. (something like "ignoreFailing")

If wished for, I would make a PR in some days (probably on the weekend).

**Comment by paras-malhotra** [comment]
@Jubeki, if we have the exit status of the Enlightn command as 0 for success and 1 if any analyzer failed, would that solve the purpose?

For ignoring analyzers, you can use the `exclude_analyzers` (blacklist) and `analyzers` (whitelist) configuration options.

**Comment by Jubeki** [comment]
I think this should work yeah

**Comment by Jubeki** [comment]
Great work by the way 👍

**Comment by paras-malhotra** [comment]
Great, thanks for the feature request! I'll work on this shortly.

**Comment by paras-malhotra** [comment]
@Jubeki this has been implemented now by @m1guelpf and will be available in the next release (today or tomorrow). 🚀

**Comment by Jubeki** [comment]
Thanks for this feature! 🙂
