### ISSUE TITLE
[Bug Report]  Failed to download

### ISSUE THREAD

**Issue by rzkhrv** [enlightn/enlightn#105]
```
 Failed to download enlightn/enlightnpro from dist: Invalid credentials for 'https://satis.laravel-enlightn.com/dist/enlightn/enlightnpro/enlightn-enlightnpro-982735cee097347c6de4db6f6ca662b943dec975-zip-d22a4b.zip', aborting.
    Now trying to download from source

```

Unable to install package. What's wrong?

**Comment by paras-malhotra** [comment]
@rzkhrv based on the error message, the credentials are invalid. Please refer to the steps in the docs here: https://www.laravel-enlightn.com/docs/getting-started/installation.html#installing-enlightn-pro
