### ISSUE TITLE
[Bug Report] UnusedGlobalMiddlewareAnalyzer outdated for L9

### ISSUE THREAD

**Issue by denydias** [enlightn/enlightn#106]
### Versions

* PHP version: 8.1.4
* Laravel version: 9.7.0
* Enlightn version: 1.25
* Enlightn Pro version (if applicable): 1.16.0

### Description

UnusedGlobalMiddlewareAnalyzer reports this:

> Your application contains global middleware that is not currently being used. It is recommended to remove these middleware from your Kernel class to enhance performance slightly. Your unused middleware include: [TrustHosts]

But the analyzer is looking for use `Fideloper\Proxy\TrustProxies`, which in Laravel 9 was [replaced](https://laravel.com/docs/9.x/upgrade#the-assert-deleted-method) by `Illuminate\Http\Middleware\TrustProxies` and should be implemented with `App\Http\Middleware\TrustProxies`.

Also, all checks for `trustedproxy.proxies` are obsolete in L9.

### Steps to Reproduce

1. Using L9, setup [TrustProxies](https://laravel.com/docs/9.x/requests#configuring-trusted-proxies) and [TrustHosts](https://laravel.com/docs/9.x/requests#configuring-trusted-hosts);
2. Run `php artisan enlightn 'Enlightn\Enlightn\Analyzers\Performance\UnusedGlobalMiddlewareAnalyzer`;
3. Bang!

**Expected behavior:**

The test should pass.

**Actual behavior:**

The test fails.

### Additional Information

N/A

**Comment by paras-malhotra** [comment]
Thanks for reporting this, just confirmed that this is a bug. Will work on a fix soon.

**Comment by denydias** [comment]
You're welcome. I'm looking forward for the fix. Thanks.

**Comment by paras-malhotra** [comment]
Fixed in #115
