### ISSUE TITLE
[Bug Report] Securing allow_url_fopen crashes Guzzle

### ISSUE THREAD

**Issue by denydias** [enlightn/enlightn#107]
### Versions

* PHP version: 8.1.4
* Laravel version: 9.7.0
* Enlightn version: 1.25
* Enlightn Pro version (if applicable): 1.16.0

### Description

When setting `allow_url_fopen=Off` (or 0) as suggested by `Analyzers\Security\PHPIniAnalyzer`, Enlightn crashes with the following unhandled exception:

```
> $ php artisan enlightn -vvv
>
>In Utils.php line 102:
>
> [RuntimeException]                                                                    
> GuzzleHttp requires cURL, the allow_url_fopen ini setting, or a custom HTTP handler.  
>
>Exception trace:
> at /var/www/html/vendor/guzzlehttp/guzzle/src/Utils.php:102
> GuzzleHttp\Utils::chooseHandler() at /var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php:49
> GuzzleHttp\HandlerStack::create() at /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php:60
> GuzzleHttp\Client->__construct() at /var/www/html/vendor/enlightn/enlightn/src/Reporting/Client.php:21
> Enlightn\Enlightn\Reporting\Client->__construct() at /var/www/html/vendor/enlightn/enlightn/src/EnlightnServiceProvider.php:63
(additional trace redacted)
```

If leaving it enabled, then the analyzer states:

```
Check n/N: Your PHP configuration is secure. Failed
Your application does not set secure php.ini configuration values. This may expose your application to security vulnerabilities. Unless there is a very specific use case for your application, it is recommended to set your php.ini configuration as follows: [allow_url_fopen: Off or 0].
Documentation URL: https://www.laravel-enlightn.com/docs/security/php-ini-analyzer.html
```

### Steps to Reproduce

1. Edit `php.ini` (both CLI and FPM) to set `allow_url_fopen=Off`;
2. Run Enlightn;
3. Bang!

**Expected behavior:**

Enlightn running just fine.

**Actual behavior:**

Enlightn crashes.

### Additional Information

N/A

**Comment by paras-malhotra** [comment]
Hi @denydias, Enlightn uses Guzzle to fire HTTP requests to your application to check for security (e.g. headers, etc.). `allow_url_fopen` should not be enabled to minimize escalating LFIs/RFIs. You can read more about this [here](https://www.laravel-enlightn.com/docs/security/php-ini-analyzer.html).

Instead, to solve this you may install cURL on the node that is running Enlightn.

**Comment by denydias** [comment]
Thanks for replying. Actually cURL was already installed. What was missing was `php-curl` extension.

These requirements (cURL + php-curl extension) may get its way to documentation, as there's no mention there they are required.
