### ISSUE TITLE
[Feature Request] Support PHP 8.1 features

### ISSUE THREAD

**Issue by dpash** [enlightn/enlightn#110]
**Is your feature request related to a problem? Please describe.**
Enlightn doesn't support at least enums or intersection types. This causes problems with at least the undefined constants check and the invalid method call check.

**Describe the solution you'd like**
Upgrade the PHP parser to the most recent version, which does now support PHP 8.1

**Describe alternatives you've considered**
Ignoring the failing checks.

**Comment by paras-malhotra** [comment]
I looked into this. PHP 8.1 is already supported since `nikic/php-parser` is locked at `^4.0` and PHP 8.1 enum support was added in `4.13.2`. So all it really needs is a `composer update` on your project. Enlightn already supports the PHP 8.1 parser.

**Comment by dpash** [comment]
I have v4.14.0 of `nikic/php-parser` installed and I'm still getting errors about lines with enums on

    Check 41/64: Your application does not rely on undefined constants. Failed
    Your application seems to reference undefined constants.
    At app/Http/Controllers/Api/OrdersStatsController.php: line(s): 74, 76, 77, 79, 80, 81, 82, 83, 128, 129, 130 and 143.

I noticed that phpstan also reports the same errors. Support for enums was added in phpstan 1.3.0, while Enlightn is restricted to <1.2.0, so perhaps this is where that error is coming from?

**Comment by paras-malhotra** [comment]
@dpash Enlightn is no longer restricted to < 1.2. Try running a `composer update`.

**Comment by dpash** [comment]
It turned out that composer was stuck unable to upgrade enlighten, larastan and phpstan due to being confused about current and new dependencies. After forcing composer to update everything, I can confirm that everything is working correctly. Thanks
