### ISSUE TITLE
[Bug Report] Cannot install Pro Version 2.0

### ISSUE THREAD

**Issue by waelsjaber** [enlightn/enlightn#119]
### Versions

* PHP version: 8.1.3
* Laravel version:  9.15
* Enlightn version: ^2.1
* Enlightn Pro version (if applicable): ^2.0

### Description
![image](https://user-images.githubusercontent.com/58438216/173860366-ff28f9f4-a86f-43b0-a3d6-420b51db3d90.png)

When I try to install the pro version on my project. I faced the issue like in the above image. 

### Steps to Reproduce
Just try to install the pro version from [here](https://www.laravel-enlightn.com/docs/getting-started/installation.html#installing-enlightn-pro)

**Comment by paras-malhotra** [comment]
Hi @waelsjaber, our Satis repository seems to have briefly gone offline for a few minutes. Can you retry the install? It should work. Feel free to reply to this thread if you face any issues.

**Comment by waelsjaber** [comment]
Hi @paras-malhotra, thank you for your reply. I'm still facing this issue since two days ago, and it hasn't been resolved yet. So, Can you please check it from your side?

**Comment by Fadelwahed** [comment]
Still the issue not resolved

**Comment by paras-malhotra** [comment]
@waelsjaber I checked and it is working for me/my credentials. If you're facing any issues please email your `auth.json` credentials to support [at] laravel-enlightn [dot com].

**Comment by waelsjaber** [comment]
Hi @paras-malhotra ,
We installed the pro version successfully on our project. But when we run the command: `php artisan enlightn --report`, the attached message shows up, please see the screenshot

![enlightn-bug-run2](https://user-images.githubusercontent.com/58438216/174082956-79e5b5b6-215b-4526-a384-3018a2c810e4.png)
