### ISSUE TITLE
[Bug Report] CacheBustingAnalyzer ignores Mix inProduction

### ISSUE THREAD

**Issue by Minhyme** [enlightn/enlightn#120]
### Versions

* PHP version: 8.1
* Laravel version: 9.11.0
* Enlightn version: 1.25.0
* Enlightn Pro version (if applicable):

### Description

Enlightn\EnlightnPro\Analyzers\Reliability\CacheBustingAnalyzer fails although Laravel docs suggest only versioning in production.

### Steps to Reproduce

Run analyzer in non production environment

**Expected behavior:**

Success

**Actual behavior:**

Failure

### Additional Information

Perhaps static code analysis of webpack.mix.js to ensure ```.version()``` is called?

**Comment by paras-malhotra** [comment]
Thanks for reporting this. This is now fixed in Enlightn Pro v1.2.0. This check will be skipped for local environments.
