### ISSUE TITLE
[PRO] license issue 

### ISSUE THREAD

**Issue by waelsjaber** [enlightn/enlightn#123]
### Versions

* PHP version: 8.1.3
* Laravel version:  9.15
* Enlightn version: ^2.1
* Enlightn Pro version (if applicable): ^2.0

### Description

We purchased the Business & Teams plan, and when we add a new project and choose the license option, there is only none option, and we are also not allowed to add team members
Pictures will be attached via e-mail

![enlightn-bug-account](https://user-images.githubusercontent.com/58438216/174089407-6e3bf513-f0d1-4527-8ff5-5dcc8f920090.png)

**Comment by paras-malhotra** [comment]
@waelsjaber it attaches the license to the first project you have or creates a new project if you don't have one when you purchase the license. You can edit that project (which is assigned the business license) and use that specific key.

Feel free to email support [at] laravel-enlightn [dot com] if you would like any assistance on this.

**Comment by waelsjaber** [comment]
> @waelsjaber it attaches the license to the first project you have or creates a new project if you don't have one when you purchase the license. You can edit that project (which is assigned the business license) and use that specific key.
> 
> Feel free to email support [at] laravel-enlightn [dot com] if you would like any assistance on this.

The License key is just for one project or for multiple projects 

Best,
