### ISSUE TITLE
[Bug Report] composer.json false possitive check

### ISSUE THREAD

**Issue by LocalHeroPro** [enlightn/enlightn#125]
### Versions

* PHP version: 8.1.8
* Laravel version: 9.19.0
* Enlightn version: 2.1.0
* Enlightn Pro version (if applicable):

### Description
Check say composer.json is bad, but is good.

### Steps to Reproduce
```bash
$ php artisan enlightn --details
//
Check 21/64: Your application's composer.json file is valid. Failed
Your application's composer.json file is not valid. Run the composer validate command to view more details.
Documentation URL: https://www.laravel-enlightn.com/docs/reliability/composer-validation-analyzer.html
//
$ composer validate
./composer.json is valid
```

**Expected behavior:**
Show valid composer.json file if is valid.

**Actual behavior:**
Enlightn showing that composer.json is invalid.

### Additional Information

none.

**Comment by paras-malhotra** [comment]
I'm unable to replicate this issue on my end. Also, its wierd that `composer validate` returns "is valid". That's exactly what the code checks:

https://github.com/enlightn/enlightn/blob/eb662815dc4aeb042c0af6e54ef99c85fb930a4f/src/Analyzers/Reliability/ComposerValidationAnalyzer.php#L48-L53

The tests are also passing:
https://github.com/enlightn/enlightn/blob/eb662815dc4aeb042c0af6e54ef99c85fb930a4f/tests/Analyzers/Reliability/ComposerValidationAnalyzerTest.php#L22-L30

**Comment by LocalHeroPro** [comment]
It's return `./composer.json is valid`. That is all output in new line.

**Comment by paras-malhotra** [comment]
> It's return `./composer.json is valid`. That is all output in new line.

Yes, the command checks whether `is valid` is in the string returned. So, the code looks fine. If you can pinpoint the exact error, I'll be happy to reopen this but I'm unable to replicate this issue and the code seems to be fine.
