### ISSUE TITLE
Horizon uses a separate sub-domain with its own set of cookies to protect against session hijacking

### ISSUE THREAD

**Issue by pratikshap31** [enlightn/enlightn#128]
### Discussed in https://github.com/enlightn/enlightn/discussions/126

<div type='discussions-op-text'>

<sup>Originally posted by **pratikshap31** July 18, 2022</sup>
 I am getting session cookies domain error while running the enlightn package.
 
 Check 92/126: Horizon uses a separate sub-domain with its own set of cookies to protect against session hijacking. Failed
While Horizon is currently using a separate domain, your application session cookies are still shared with Horizon. This exposes your application to session hijacking, where if either your main application or Horizon is compromised, then the other would also be compromised. It is recommended to configure separate cookies by setting the session domain configuration to null.
At config/session.php, line 158.
Documentation URL: https://www.laravel-enlightn.com/docs/security/horizon-security-analyzer.html

- My application has multiple subdomains. each user has his own subdomain. 
- if I remove the URL and set null for session_domain it will return page 404 when i logged in to any user account

- how to solve this ?
</div>

**Comment by paras-malhotra** [comment]
This seems to be an issue specify to your application - I don't think we can pinpoint the exact correction without knowing how your app manages sessions.

Essentially, the idea is that Horizon shouldn't share the same session cookies with your application login, otherwise any attack on the application can escalate to admin interfaces such as Horizon.

**Comment by pratikshap31** [comment]
@paras-malhotra 

we have multiple subdomains. each user has their own subdomain. 
I am using session_domain to manage session cookies. The value of the session domain is ".projectame.com".
I am facing a redirect issue when putting a null value for session_domain.

**Comment by pratikshap31** [comment]
@paras-malhotra 
I have multiple subdomains. each user has their own subdomain. I have the primary subdomain “my”. I am using session_domain to manage session cookies. The value of the session domain is “.projectame.com”. I am facing a redirect issue when putting a null value for session_domain.
when the session domain is null, I am having an issue redirecting from my.projectname.com to username.projectname.com.
Does anyone know how to solve it?
