### ISSUE TITLE
[Bug Report] artisan enlightn:baseline doesnt populate the ignore_errors array with expected values 

### ISSUE THREAD

**Issue by paulpreibisch** [enlightn/enlightn#129]
### Versions

* PHP version: 8.1
* Laravel version: 9.2
* Enlightn version: 2.1 
* Enlightn Pro version (if applicable): 2.1

### Description

When I run

`php -d memory_limit=10G artisan enlightn --ci`

Several analyzers report issues:
+----------------+-------------+-------------+-----------+-----------+
| Status         | Performance | Reliability |  Security |     Total |
+----------------+-------------+-------------+-----------+-----------+
| Passed         |    7  (58%) |   22  (71%) | 31  (86%) | 60  (76%) |
| Failed         |    1   (8%) |    4  (13%) |  4  (11%) |  9  (11%) |
| Not Applicable |    4  (33%) |    5  (16%) |  1   (3%) | 10  (13%) |
| Error          |    0   (0%) |    0   (0%) |  0   (0%) |  0   (0%) |
+----------------+-------------+-------------+-----------+-----------+

However, when I run 

`php -d memory_limit=10G artisan enlightn:baseline --ci`

The progress bar starts moving very slowly, and then after 3/79, it jumps to complete immediately.
Upon checking the 'ignore_errors' array in enlightn.php however, only one analyzer is listed

```
'ignore_errors' => [
        Enlightn\EnlightnPro\Analyzers\Security\DebugStatementAnalyzer::class => [
            [
                'path' => 'app/OURAPP/TestHelpers/CurrentApiTestTrait.php', 'details' => 'Function print_r called.'
            ]
        ]
    ],
```

### Steps to Reproduce
1) run `php -d memory_limit=10G artisan enlightn --ci`
2) Observe and take a note of the problems reported
3) run `php -d memory_limit=10G artisan enlightn:baseline --ci` 
4) Notice that the ignore_errors array is not populated with reported analyzers listed in step 1

**Expected behavior:**

'ignore_errors' array should have the same analyzers which reported problems in first run listed

**Actual behavior:**
```
'ignore_errors' array only has one analyzer listed
'ignore_errors' => [
        Enlightn\EnlightnPro\Analyzers\Security\DebugStatementAnalyzer::class => [
            [
                'path' => 'app/OURAPP/TestHelpers/CurrentApiTestTrait.php', 'details' => 'Function print_r called.'
            ]
        ]
    ],
```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by paras-malhotra** [comment]
Which analyzers failed in your first run? Some analyzers are only flagged as `dont_report` if they don't include a line by line code assessment (e.g. the config caching analyzer).

**Comment by paulpreibisch** [comment]
Hi, thanks for getting back to us.

Here is a list of exceptions and failures.  Please let me know if there is other information you need

* Check 3/79: Your application uses an efficient rate limiting mechanism for queued jobs. Exception
Class "App\Repositories\BaseRepository" not found

* Check 4/79: Your application uses an efficient throttling mechanism. Failed
Your application uses the "ThrottleRequests" middleware shipped with Laravel but does not use the "ThrottleRequestsWithRedis" middleware, even though your application is using Redis. The Redis specific middleware is more efficient in managing rate limiting using Redis and you should consider using the Redis specific middleware instead.

* Check 9/79: A proper queue driver is configured. Failed
Your queue driver is set to sync. This means that all jobs, mails, notifications and event listeners will be processed immediately in a synchronous manner. These time consuming tasks will slow down web requests and this driver is not suitable for production environments. Even for local development, it is recommended to use other drivers in order to accurately simulate production behaviour.

* Check 12/79: Your application does not contain unused global HTTP middleware. Failed
Your application contains global middleware that is not currently being used. It is recommended to remove these middleware from your Kernel class to enhance performance slightly. Your unused middleware include: [TrustProxies]

Check 13/79: Your application is configured to re-publish package assets on update. Failed
Your application's composer.json file does not include recommended post-update-cmd scripts to re-publish your package assets on update. Affected packages include: Telescope
Documentation URL: https://www.laravel-enlightn.com/docs/reliability/composer-package-publish-analyzer.html

* Check 26/79: All env variables used in your .env file are defined in your .env.example file. Failed
Your application has some missing environment variables that are defined in your .env file but missing in your .env.example file

* Check 28/79: All env variables defined in your example file are set in your .env file. Failed
Your application has some missing environment variables that are defined in your .env.example file but missing in your .env file: MAX_UPLOAD_SIZE
Documentation URL: https://www.laravel-enlightn.com/docs/reliability/env-variable-analyzer.html

* Check 48/79: Your application does not contain debug statements. Exception
Cannot access offset of type string on string
Documentation URL: https://www.laravel-enlightn.com/docs/security/debug-statement-analyzer.html

**Comment by paulpreibisch** [comment]
Do you need anything more on my end?

**Comment by paras-malhotra** [comment]
@paulpreibisch the `enlightn:baseline` does not ignore exceptions - those need to be fixed in your application.

For the others, if it's related to a specific line number (in code), it updates the `ignore_errors` config and if it's not related to a specific line in code (e.g. unused global HTTP middleware or throttling), it updates the `dont_report` config instead.

I don't think the behaviour you've reported is a bug because the list of errors you shared aren't related to a specific line, and so only the `print_r` call is ignored.

Hope this helps!
