### ISSUE TITLE
Shows composer.json file is invalid though it is valid

### ISSUE THREAD

**Issue by prashantbw** [enlightn/enlightn#132]
Hi,
   
   
* PHP version:7.4.26
* Laravel version:8.83.19
* Enlightn version: 2.1.0
* Enlightn Pro version (if applicable): -

### Description
When I run enlightn, for composer.json check it shows failed.

```
  Your application's composer.json file is valid. Failed
Your application's composer.json file is not valid. Run the composer validate command to view more details.
```
If I check it with "composer validate" command it shows composer.json is valid.

Is it false positive or am I missing something?

**Comment by ordago** [comment]
```
λ composer validate
./composer.json is valid
```

Can you paste the exact output of the validate command?

**Comment by prashantbw** [comment]
@ordago when you say exact I din't get your question, follwoing is the command I am running and the output what I see
Command
```
 composer validate ./composer.json 

```
output
`./composer.json is valid`

**Comment by ordago** [comment]
https://github.com/enlightn/enlightn/blob/eb662815dc4aeb042c0af6e54ef99c85fb930a4f/src/Analyzers/Reliability/ComposerValidationAnalyzer.php#L50-L51

If you check the code of the validator you can see that it call the command and checks that the 'is valid' string is present.  So it seems it should work.

**Comment by prashantbw** [comment]
Thanks @ordago looks like it may be  because I don't have global composer.json setup, it may be picking that error? not sure

when I run command 

`composer validate -vvv`

I see one line at the end like this

`Failed to initialize global composer: Composer could not find the config file: /Users/mypc/.composer/composer.json`

**Comment by dhanyn10** [comment]
@prashantbw how do you solve that?
