### ISSUE TITLE
[Bug Report] Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by samehdoush** [enlightn/enlightn#134]
### Versions

* PHP version: 8.1
* Laravel version: 9.23
* Enlightn version:  2.1

### Description
Your requirements could not be resolved to an installable set of packages.
 Problem 1
    - Root composer.json requires enlightn/enlightn ^2.1 -> satisfiable by enlightn/enlightn[v2.1.0, 2.x-dev].
    - enlightn/enlightn[v2.1.0, ..., 2.x-dev] require nunomaduro/larastan ^2.0 -> found nunomaduro/larastan[dev-master, 2.0.0, ..., v2.1.12] but the package is fixed to 1.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    

### Steps to Reproduce
composer require enlightn/enlightn

### composer.json
    "require": {
        "php": "^8.0.2",
        "akaunting/laravel-setting": "^1.2",
        "beyondcode/laravel-websockets": "^1.13",
        "guzzlehttp/guzzle": "^7.2",
        "inertiajs/inertia-laravel": "^0.5.2",
        "laravel/framework": "^9.19",
        "laravel/jetstream": "^2.9",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "league/flysystem-aws-s3-v3": "3.0",
        "maatwebsite/excel": "^3.1",
        "mcamara/laravel-localization": "^1.7",
        "mehdi-fathi/eloquent-filter": "^2.6",
        "propaganistas/laravel-phone": "^4.3",
        "psr/simple-cache": "1.0",
        "pusher/pusher-php-server": "^7.0",
        "spatie/laravel-backup": "^8.1",
        "spatie/laravel-google-cloud-storage": "^2.0",
        "spatie/laravel-medialibrary": "10.0.0",
        "spatie/laravel-permission": "^5.5",
        "spatie/laravel-sitemap": "^6.2",
        "tightenco/ziggy": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.6",
        "barryvdh/laravel-ide-helper": "^2.12",
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^0.2.3",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },

**Comment by paras-malhotra** [comment]
This doesn't seem to be a bug. `Composer.lock` seems to have locked Larastan to 1.0.3. I guess you need to delete the lock file and try a fresh composer install
