### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by dustingtaylor** [enlightn/enlightn#139]
### Versions

* PHP version: 7.4
* Laravel version: 8.0
* Enlightn version: latest
* Enlightn Pro version (if applicable): 1.0+

### Description

Enlightn bot is no longer making comments on Pull Requests. How can I get it working again for private repositories?

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:**

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by dustingtaylor** [comment]
This is a pro license.

**Comment by paras-malhotra** [comment]
Hey @dustingtaylor, can you send across an email to support [at] laravel-enlightn [dot com] along with a link to a sample PR you're referring to?

We'll look into it asap, thanks!
