### ISSUE TITLE
[Feature Request] Encourage using native Laravel safety mechanisms

### ISSUE THREAD

**Issue by Baspa** [enlightn/enlightn#143]
The feature request is not necessarily related to a problem but it will definitely prevent problems.

The solution I am proposing is to add one or more analysers that can check if certain methods are used in the 'AppServiceProvider' like:

- `Model::preventLazyLoading();` to prevent N+1 problems. 
- `Model::preventAccessingMissingAttributes();` to protect against partially hydrated models
- `Model::preventSilentlyDiscardingAttributes();` to encourage model strictness 

More in depth information about those methods: https://planetscale.com/blog/laravels-safety-mechanisms. It requires at least Laravel 9.35.0 though. 

If interested I can look at making a PR for this.

**Comment by paras-malhotra** [comment]
I think this boils down to style. It's a feature that people can use but I don't think it needs to be forced at this stage. We already [detect N+1 issues](https://www.laravel-enlightn.com/docs/performance/telescope-nplusone-query-analyzer.html) and many other performance checks in Enlightn, so we don't need to force developers to use this.
