### ISSUE TITLE
[Feature Request] laravel 10 support

### ISSUE THREAD

**Issue by ariaieboy** [enlightn/enlightn#144]
Laravel 10 will release in less than a week can we add laravel 10 support for enlightn?

**Comment by repat** [comment]
@paras-malhotra bump :)

**Comment by paras-malhotra** [comment]
We're working on this. There are a few package dependencies that we might have to wait on. We expect to release Laravel 10 compatibility by the end of this month.

**Comment by craigpaul** [comment]
@paras-malhotra Do you expect Laravel 10 to require a different license from Laravel 6-9?

**Comment by paras-malhotra** [comment]
@craigpaul it will be covered in the same license as long as it is used with the same project. So, if you're upgrading to Laravel 10 on the same project, you won't need to buy a separate license

**Comment by paras-malhotra** [comment]
Support for Laravel 10.x is now available in Enlightn v2.3.0 via #145
