### ISSUE TITLE
[Bug Report] memory exhausted running Elightn

### ISSUE THREAD

**Issue by awaegel-rm** [enlightn/enlightn#152]
### Versions

* PHP version: 8.1.21
* Laravel version: 10.14.1
* Enlightn version: v2.3.0
* Enlightn Pro version (if applicable): v2.3.0

### Description

After running test #41 in EnlighnPro, Artisan throws an 'out of memory' error

### Steps to Reproduce

Run 'php artisan enlightn'

**Expected behavior:**

Package runs successfully.

**Actual behavior:**

Package does not run successfully.

### Additional Information

Here's the output where it happened:

|------------------------------------------
| Running Reliability Checks
|------------------------------------------

Check 38/128: Your application uses cache busting. Passed

Check 39/128: Your application is configured to re-publish package assets on update. Failed
Your application's composer.json file does not include recommended post-update-cmd scripts to re-publish your package assets on update. Affected packages include: Horizon and Telescope
Documentation URL: https://www.laravel-enlightn.com/docs/reliability/composer-package-publish-analyzer.html

Check 40/128: Your application does not contain any dead routes. Passed

Check 41/128: Your application has sufficient disk space. Passed
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 147456 bytes) in /home/runcloud/webapps/redefine-dev3/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 421

   Symfony\Component\ErrorHandler\Error\FatalError

  Allowed memory size of 268435456 bytes exhausted (tried to allocate 147456 bytes)

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:421
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /home/runcloud/webapps/redefine-dev3/vendor/nunomaduro/collision/src/Highlighter.php on line 135
PHP Warning:  Packets out of order. Expected 228 received 146. Packet size=2048 in Unknown on line 0
runcloud@redefine-sandbox:~/webapps/redefine-dev3$

**Comment by paras-malhotra** [comment]
Fixed in #151
