### ISSUE TITLE
Enlightn run very slowly take 2 minute to run

### ISSUE THREAD

**Issue by prathna124** [enlightn/enlightn#162]
Enlightn run very slowly take 2 minute to run

I use  "enlightn/enlightnpro": "1.*",  laravel 8 , php 8.1

When i hit php artisan enlightn command it consuming more time to run and when I run on production my site is down

We have try to resolve this using below step:
1. We have install queue setup and this slow down so we have uninstall and remove queue configuration still faced issue
2. We have also try this php -d memory_limit=512M artisan enlightn still same issue faced 
3. We have install and uninstall enlightn still faced same issue
4. I have check my local system space also is there not issue regarding space

Please guide me on what is issue ? Why enlightn run very slow ?

**Comment by paras-malhotra** [comment]
There are some checks that may take considerable time - specifically the Telescope checks for slow queries, etc. You could possibly try running Enlightn with these dynamic analysis checks disabled.

I'm closing this issue. If you have any questions, feel free to comment here and I'll be happy to help!

**Comment by drewbindon** [comment]
@paras-malhotra We actually have a similar problem - in one of our projects the enlightn scan takes around 10 minutes to fully complete in our CI - around 5 minutes locally (we are using Elightn pro as well). Is there a way to get some output for the amount of time each check takes to complete to see where the problem might be? We don't use Telescope so none of those dynamic checks are running, as far as I understand. Trying to avoid having to disable each analyzer one-by-one if I can.
