### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by neomaximus2k** [enlightn/enlightn#165]
When using the --report feature I am receiving the following:

```
+----------------+-------------+-------------+----------+-----------+

   Enlightn\Enlightn\Reporting\BadResponseException 

  Bad response: {
    "message": "Server Error"
}

  at vendor/enlightn/enlightn/src/Reporting/Client.php:99
     95▕             throw new UnauthorizedException("Invalid credentials. Please check your username and API token.");
     96▕         }
     97▕ 
     98▕         if ($statusCode !== 200 && $statusCode !== 204) {
  ➜  99▕             throw new BadResponseException("Bad response: ".$response->getBody());
    100▕         }
    101▕ 
    102▕         $responseData = json_decode($response->getBody(), true);
    103▕ 

      +15 vendor frames 

  16  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

I have attempted this on a physical server and from within a docker container and both throw the error.

**Comment by paras-malhotra** [comment]
The error is displayed in the exception: Invalid credentials. Please check your username and API token.

You may refer the docs for the credentials here: https://www.laravel-enlightn.com/docs/getting-started/usage.html#credentials-for-the-web-ui

**Comment by paras-malhotra** [comment]
I'm closing this issue as resolved. Feel free to write here if you have any questions

**Comment by neomaximus2k** [comment]
erm... Either I've missread the code or you have, the line is 99 where the issue is, not the unauthorized exception

**Comment by paras-malhotra** [comment]
Ohh my bad, were you able to resolve this or is this still happening? Can you try re-running?

**Comment by neomaximus2k** [comment]
Just ran the scan again and it is now working, I imagine the remote system went down hence the error 500.
