### ISSUE TITLE
Dependancy updates

### ISSUE THREAD

**Issue by stephenstack** [enlightn/enlightn#178]
Can the following get updated?

"laravel/framework": "^9.0|^10.0", to 11
"nikic/php-parser": "^4.0",  to 5.0

**Comment by paras-malhotra** [comment]
Laravel 11.x is now supported via #179 and available in Enlightn v2.8. Working on nikic/php-parser, so I'll keep this issue open to track.

**Comment by paras-malhotra** [comment]
nikic/php-parser 5.x is also supported now via #183 and available in Enlightn v2.10. So, closing this.
