### ISSUE TITLE
[Bug Report] Issue with upgraded Laravel 11 app and the unused global HTTP middleware check (8/47)

### ISSUE THREAD

**Issue by u01jmg3** [enlightn/enlightn#185]
### Versions

* PHP version: 8.2.17
* Laravel version: 11.3.1
* Enlightn version: 2.10.0

### Description

I've just upgraded my application from Laravel 10 to 11 and moved my middleware to `bootstrap/app.php` and the [`withMiddleware()`](https://laravel.com/docs/11.x/middleware#global-middleware) method. This means I have no need for `App\Http\Kernel.php` and have deleted the file. Enlighten is now failing on a check that previously passed:

> Check 8/47: Your application does not contain unused global HTTP middleware. Failed
>
> Your application contains global middleware that is not currently being used. It is recommended to remove these middleware from your Kernel class to enhance performance slightly. Your unused middleware include: [TrustProxies]
Documentation URL: https://www.laravel-enlightn.com/docs/performance/unused-global-middleware-analyzer.html

To note, I have no TrustProxies middleware present in my app.

### Steps to Reproduce

- Create a Laravel 11 application
- Ensure `App\Http\Kernel.php` does not exist
- Run `php artisan enlightn --ci --details`

**Expected behavior:**

-  Check 8/47 should pass

**Actual behavior:**

-  Check 8/47 instead fails

**Comment by u01jmg3** [comment]
I managed to sort out my issue. I needed to define what middleware Laravel 11 now automatically applies.

- See [Manually Managing Laravel's Default Global Middleware](https://laravel.com/docs/11.x/middleware#manually-managing-laravels-default-global-middleware)

```php
->withMiddleware(function (Middleware $middleware) {
    $middleware->use([
        // \Illuminate\Http\Middleware\TrustHosts::class,
        // \Illuminate\Http\Middleware\TrustProxies::class, // <-- Comment out for analyzer 8/47 to pass
        \Illuminate\Http\Middleware\HandleCors::class,
        \Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance::class,
        \Illuminate\Http\Middleware\ValidatePostSize::class,
        \Illuminate\Foundation\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
    ]);
})
```

**Comment by u01jmg3** [comment]
It might also be worth updating your docs now that the middleware setup no longer just lives in `App\Http\Kernel.php`.

**Comment by paras-malhotra** [comment]
Thanks! Added via https://github.com/enlightn/enlightn-docs/pull/42. Docs link: https://www.laravel-enlightn.com/docs/performance/unused-global-middleware-analyzer.html
