### ISSUE TITLE
[Bug Report] Worng percentage

### ISSUE THREAD

**Issue by svikramjeet** [enlightn/enlightn#21]
### Versions

* PHP version: 7.4
* Laravel version: 8.25
* Enlightn version: 1.7
* Enlightn Pro version (if applicable):

### Description

+----------------+-------------+-------------+----------+---------------------+
| Status               | Performance | Reliability | Security |    Total |
+----------------+-------------+-------------+----------+--------------------+
| Passed             |    11 (55%) |    19 (61%) | 11 (44%) | 41 (54%) |
| Failed               |     3 (15%)  |     6 (19%)  |  6 (24%) | 15 (20%) |
| Not Applicable  |     3 (15%) |     0  (0%)    |  2  (8%) |  5  (7%) |
| Error                 |     0  (0%)  |     0  (0%)    |  0  (0%) |  0  (0%) |
+----------------+-------------+-------------+----------+----------+

### Additional Information

41/61 is not 54%

**Comment by paras-malhotra** [comment]
Thanks for the bug report @svikramjeet, this is fixed in v1.7.1.
