### ISSUE TITLE
session()->has('value') Being seen as an invalid method call by Enlightn

### ISSUE THREAD

**Issue by Orillian** [enlightn/enlightn#24]
In some parts of my project I use a lot of session data, that means there is a lot of checks to session()->has() and session()->exists().

I started running Enlightn the other day and it was able to find some obscure edge cases and missing types, and overall I was impressed! Then further down the list I can across the Enlightn\Enlightn\Analyzers\Reliability\InvalidMethodCallAnalyzer and it had dozens of lines flagged across a number of controllers.

Almost every single one is a session()->has() check akin to what you see here https://laravel.com/docs/8.x/session#determining-if-an-item-exists-in-the-session

Call me dense, but I'm not sure I understand why these are appearing.  Maybe I'm missing something obvious, but I'm about as stumped as it gets.

Thanks for any feedback you can give!

**Comment by paras-malhotra** [comment]
The reliability checks are not perfectly accurate given the limitations of static analysis. Some of the reliability checks use [PHPStan](https://github.com/phpstan/phpstan) in the background including the `InvalidMethodCallAnalyzer`.

I can explain to you why exactly this is happening:
1. PHPStan uses docblock and method signatures to understand what a method can return.
2. The `session` helper function can return a `Illuminate\Session\Store` or a `Illuminate\Session\SessionManager` as [here](https://github.com/laravel/framework/blob/44e5d47e7297807e5c95940871ed03a74e0bc331/src/Illuminate/Foundation/helpers.php#L740-L749).
3. When you called `session()->has()`, PHPStan went to check if `Illuminate\Session\Store` has a `has` method. Indeed it does. All good so far.
4. It then goes to check if `Illuminate\Session\SessionManager` has a `has` method and no it doesn't. Now, `SessionManager` actually forwards calls to the driver (through the `__call` magic method), which is an instance of `Illuminate\Session\Store` but that cannot be known just by static analysis (looking at the docblock or the method signature). 

So PHPStan flags it as an error. It assumes that there could be edge case scenarios where a `SessionManager` is returned by the `session()` helper, and the `has` method does not exist, which will make the code fail.

Hope that helps! I guess these are the limitations of static analysis.

I am closing this issue. If you have any further questions, feel free to bump this thread. I will reply here. In case there's another issue, feel free to open a new one. Thanks!

**Comment by Orillian** [comment]
@paras-malhotra Thanks for the run down! I knew it would be a easy answer! 

> Hope that helps!

It helped a lot. 

>  I guess these are the limitations of static analysis.

You're not wrong, but it's still handy when it works! A lot of what I do would be a lot harder without them!
