### ISSUE TITLE
Aggregation checker fails on Windows

### ISSUE THREAD

**Issue by beard7** [enlightn/enlightn#25]
### Versions

* PHP version: 7.4.1
* Laravel version: 8.25.0
* Enlightn version: 1.7
* Enlightn Pro version (if applicable):

### Description
The Aggregation checker results in `Exception Unable to launch a new process.` when run on Windows IIS

### Steps to Reproduce
Run `php artisan enlightn` on a Windows IIS server

**Comment by paras-malhotra** [comment]
@beard7 we don't support Windows for now. I'll make a note of this in the readme section.
