### ISSUE TITLE
[Bug Report] "View Caching Analyzer" incorrectly fails

### ISSUE THREAD

**Issue by diverpl** [enlightn/enlightn#41]
### Versions

* PHP version: 7.4.14
* Laravel version: 8.27.0
* Enlightn version: 1.13.0

### Description

This test counts blade files in _resources/views_ and compiled views in _storage/framework/views_. If the counts aren't equal the test fails. However there can be **more** compiled views than blade files - today I've found some compiled mail template components which were not compiled by `php artisan view:cache`. So maybe it is a good idea to change the condition slightly - the test shoud fail if there are less compiled views than blade files.

### Steps to Reproduce

Run the test "View Caching Analyzer".

**Expected behavior:**

The test should succeed if there are more or equal compiled views than blade files.

**Actual behavior:**

The test fails.

**Comment by paras-malhotra** [comment]
Hi @diverpl, thanks for reporting this. This has been fixed and will be available in the next release.
