### ISSUE TITLE
WTFPL License[Bug Report]

### ISSUE THREAD

**Issue by jasperf** [enlightn/enlightn#45]
See https://github.com/hanneskod/classtools/issues/22#event-4333269047 . The license checked needs to be updated with the WTFPL License or _Do What the Fuck You Want to Public License_ which should be whitelisted as well.

**Comment by paras-malhotra** [comment]
@jasperf, thanks for reporting this. This will be available in the next release. If you already have published your `config/enlightn.php` file, you may need to re-publish or modify the `license_whitelist` config option, since your config file overrides the default.
