### ISSUE TITLE
[Bug Report] Trustproxies is not correctly checked

### ISSUE THREAD

**Issue by potsky** [enlightn/enlightn#48]
### Versions

* PHP version: 8.0.2
* Laravel version: 8.28.1
* Enlightn version: 1.15.0

### Description

I use Trusted Proxy on Heroku with the following configuration but Enlightn tells me :

```
Check 15/59: Your application does not contain unused global HTTP middleware. Failed
Your application contains global middleware that is not currently being used. It is recommended to remove these middleware from your Kernel class to enhance performance slightly. Your unused middleware include: [TrustProxies]
Documentation URL: https://www.laravel-enlightn.com/docs/performance/unused-global-middleware-analyzer.html
```

Here is my `App\Http\Middleware\TrustProxies` class:

```
class TrustProxies extends Middleware
{
    protected $proxies = '*';

    protected $headers = Request::HEADER_X_FORWARDED_AWS_ELB;
}
```

If you check the `Fideloper\Proxy\TrustProxies` class, setting the property `$proxies = '*'` changes everything even if there is no `trustedproxy.proxies` config key as mentioned in the [documentation](https://www.laravel-enlightn.com/docs/performance/unused-global-middleware-analyzer.html)

**Comment by paras-malhotra** [comment]
@potsky, thanks for reporting this. This is fixed in v1.15.1.

**Comment by potsky** [comment]
You rock @paras-malhotra!
Your package is really useful and awesome, I have just bought it ;-)

**Comment by paras-malhotra** [comment]
@potsky glad you like it! 😊 Stay tuned, we've got some really [exciting features](https://twitter.com/Enlightn_app/status/1361963443645947908) coming up! Also, feel free to suggest any features that you'd like to see. Thanks!
