### ISSUE TITLE
[Feature Request] Support REDIS_URL in RedisSingleServerAnalyzer check

### ISSUE THREAD

**Issue by potsky** [enlightn/enlightn#50]
**Is your feature request related to a problem? Please describe.**

The `RedisSingleServerAnalyzer` test fails in production on Heroku because we use `REDIS_URL` env parameter instead of separated configuration parameters. `host`, `password` and `port` are set to default on our configuration and they could be safely deleted because `REDIS_URL` takes precedence on all others configuration parameters.

Here is the `database.php`configuration file :

```
    'redis' => [

        'client' => env('REDIS_CLIENT', 'phpredis'),

        'default' => [
            'url' => env('REDIS_URL'),
            'host' => env('REDIS_HOST', '127.0.0.1'),
            'password' => env('REDIS_PASSWORD', null),
            'port' => env('REDIS_PORT', '6379'),
            'database' => env('REDIS_DB', '0'),
        ],
```

**Describe the solution you'd like**

If `url` is set to something non empty, the test should succeed.

**Describe alternatives you've considered**

I have disabled this check on my installation and it is fine for me ;-)

**Additional context**

**Comment by paras-malhotra** [comment]
@potsky, thanks for reporting this. This is fixed in Enlightn Pro v1.10.1.
