### ISSUE TITLE
[Bug Report] Cookies are secured as HttpOnly failing

### ISSUE THREAD

**Issue by hose1021** [enlightn/enlightn#59]
### Versions

* PHP version: 8.0.3
* Laravel version: 8.33.1
* Enlightn version: 1.20.0 / 1.19.0
* Enlightn Pro version (if applicable):

### Description
Cookies are secured as HttpOnly failing bug config file is `true`

**Comment by paras-malhotra** [comment]
Hi @hose1021, what is the output for `config('session.http_only')` in [Tinker](https://laravel.com/docs/8.x/artisan#tinker)?

**Comment by hose1021** [comment]
> Hi @hose1021, what is the output of `config('session.http_only')` in [Tinker](https://laravel.com/docs/8.x/artisan#tinker)?

Is true.

I think it is my project error, sorry. `Call to undefined method Illuminate\Support\Facades\Auth::extend()`
