### ISSUE TITLE
Cookie Domain Analyzer incompatible with sanctum

### ISSUE THREAD

**Issue by CiiDyR** [enlightn/enlightn#67]
### Versions

* PHP version: 8.0.2
* Laravel version: 8.49.2
* Enlightn version: 1.22.1
* Enlightn Pro version (if applicable): 1.16.0

### Description
Currently the Pro check for https://www.laravel-enlightn.com/docs/security/cookie-domain-analyzer.html fails when you set the `SESSION_DOMAIN` to something similar to `.domain.test`. The docs say this check is skipped if the application registers subdomain routes. However, setting the domain config to something this lax is actually required when using `laravel/sanctum`. This is pretty much required when you build an API on a single domain but want to share the authentication between separate web app SPAs.
See https://laravel.com/docs/8.x/sanctum#cors-and-cookies for more information in conjunction with `laravel/sanctum`.

**Comment by paras-malhotra** [comment]
This setting is only required for Sanctum if your SPA exists on a separate sub-domain. Also, if your SPA is not in the same project repo (mono-repo), only then will this analyzer error out. In that case, I'd recommend to add this to the `exclude_analyzers` [configuration](https://www.laravel-enlightn.com/docs/getting-started/configuration.html#excluding-analyzers-from-reporting).
