### ISSUE TITLE
[Bug Report] Not supporting multiple licenses causes false-positive failure on LicenseAnalyzer

### ISSUE THREAD

**Issue by mwkcoding** [enlightn/enlightn#68]
### Versions

* PHP version: 7.4.16 & 8.0.8
* Laravel version: 8.52.0
* Enlightn version: 1.22.1
* Enlightn Pro version (if applicable):

### Description
For example, all Laravel projects using Jetstream will now be failing with Enlightn because a dependency package `nette/schema` has 3 licenses defined in `composer.json` and because TWO of them is not in the default license whitelist, this causes it to fail even though it shouldn't.

### Steps to Reproduce
1. Make new Laravel 8 project with Jetstream
2. Require Enlightn
3. Run `php artisan enlightn` and watch it fail on the LicenseAnalyzer

**Expected behavior:**
Support multiple licenses and not causing false-positives because of lack thereof.

**Actual behavior:**
Fails because no support for multiple licenses.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by paras-malhotra** [comment]
Closed by #69
