### ISSUE TITLE
[Feature Request] Support Lumen projects

### ISSUE THREAD

**Issue by MarkVaughn** [enlightn/enlightn#75]
I would like to be able to use your tool with a lumen project

currently when requiring the enlight package, it adds laravel as a dependency.
It would be cool if the tool could recognize the context it is in, possibly skipping tests that are incompatible with lumen.
```
php artisan enlightn

In Container.php line 805:
                                               
  Target class [path.storage] does not exist.  
                                               

In Container.php line 803:
                                     
  Class path.storage does not exist  
                                     
```

I understand that this might not be possible, but I didn't see any closed tickets about this, so i figured I might just ask.

**Comment by paras-malhotra** [comment]
We have no plans to support Lumen at this time.
