### ISSUE TITLE
[Feature Request] Mark lines as ignore with comment

### ISSUE THREAD

**Issue by striderwhitepderas** [enlightn/enlightn#77]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to modify the configuration to ignore a line. 

**Describe the solution you'd like**
Instead, it would be useful to mark a line as ignore with a comment, similar to Eslint ignore. Example:

```javascript
// eslint-disable-next-line no-use-before-define
var thing = new Thing();
```

**Comment by paras-malhotra** [comment]
You can use `@phpstan-ignore-next-line`. Refer the docs [here](https://phpstan.org/user-guide/ignoring-errors).
