### ISSUE TITLE
[Feature Request] upgrading Larastan and PHPStan

### ISSUE THREAD

**Issue by dannewnsjump24** [enlightn/enlightn#87]
Now that [PHPStan 1.0](https://phpstan.org/blog/phpstan-1-0-released) and [Larastan 1.0](https://github.com/nunomaduro/larastan/releases/tag/1.0.0) have been released it would be great to upgrade this excellent package to use these.  

Thanks for all the hard work thats been put into enlightn by everyone envolved.

**Comment by morawcik** [comment]
Any chance to get it done in near future?

**Comment by potsky** [comment]
Hi @paras-malhotra ! Indeed if there is no problem to switch for you, it could be really nice because PHPStan 0.7 is really a mess in last versions of Laravel...

**Comment by usernotnull** [comment]
+1

**Comment by paras-malhotra** [comment]
We will be updating the library for the Laravel 9 LTS release. That's when we'll consider the 1.0 major upgrades. Leaving this open so that it can be picked up for the Enlightn upgrade in January.

**Comment by morawcik** [comment]
Really? I'm disappointed... Guess it's time to say good bye...
