### ISSUE TITLE
[Bug Report] False positive on Pro CompressionHeaderAnalyzer when libcurl doesn't have brotli support

### ISSUE THREAD

**Issue by joekeilty-oub** [enlightn/enlightn#89]
### Versions

* PHP version: 7.4.16
* Laravel version: 8.63.0
* Enlightn version: 1.22.1
* Enlightn Pro version (if applicable): 1.16.0

### Description

The Enlightn Pro CompressionHeaderAnalyzer produces a false positive when ran on systems where the version of libcurl has not been compiled with brotli support.

A Guzzle exception is thrown:

```
GuzzleHttp\Exception\RequestException with message 'cURL error 23: Unrecognized content encoding type. libcurl understands deflate, gzip content encodings. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)'
```

If `br` is removed from the headers passed into the request (`'headers' => ['Accept-Encoding' => 'gzip, deflate, br']`) then the response goes through successfully.

### Steps to Reproduce

Run the `\Enlightn\EnlightnPro\Analyzers\Performance\CompressionHeaderAnalyzer` on a system with libcurl that doesn't support brotli. 

This is the output of my `curl_version()` (on Debian buster)

```
>>> curl_version();
=> [
     "version_number" => 475136,
     "age" => 4,
     "features" => 4179869,
     "ssl_version_number" => 0,
     "version" => "7.64.0",
     "host" => "x86_64-pc-linux-gnu",
     "ssl_version" => "OpenSSL/1.1.1g",
     "libz_version" => "1.2.11",
     "protocols" => [
       "dict",
       "file",
       "ftp",
       "ftps",
       "gopher",
       "http",
       "https",
       "imap",
       "imaps",
       "ldap",
       "ldaps",
       "pop3",
       "pop3s",
       "rtmp",
       "rtsp",
       "scp",
       "sftp",
       "smb",
       "smbs",
       "smtp",
       "smtps",
       "telnet",
       "tftp",
     ],
     "ares" => "",
     "ares_num" => 0,
     "libidn" => "2.2.0",
     "iconv_ver_num" => 0,
     "libssh_version" => "libssh2/1.8.0",
     "brotli_ver_num" => 0,
     "brotli_version" => "",
   ]
```

**Expected behavior:**

Perhaps you could detect if the version of curl used by Guzzle has support for brotli (could you use the `brotli_version` etc. fields from curl_version() or is there a guzzle method for this?), and if not, remove `br` from the headers.

**Actual behavior:**

It will include `br` in Accept-Encoding whether there is support for Brotli or not.

### Additional Information

N/A

**Comment by paras-malhotra** [comment]
I believe it is best for you to install curl with brottli support. If we remove the br header, and say your web server has Brottli only supported, it will give a false negative instead. So, I don't believe we should remove `br` from the headers in this check.

If you think I've missed something, feel free to re-open and we can discuss it.
