### ISSUE TITLE
Your application uses stable versions of dependencies. Exception

### ISSUE THREAD

**Issue by rgr** [enlightn/enlightn#90]
### Versions
* PHP version: 8.1
* Laravel version: 8.12
* Enlightn Pro version : 1.16

### Description
For every enlightn use (local, staging or prod), I get an exception with the rule 123 : 

```bash
Your application uses stable versions of dependencies. Exception
The process has been signaled with signal "9".
```

### Steps to Reproduce

**Expected behavior:**
Not applicable or Passed

**Actual behavior:**
Exception

**Comment by paras-malhotra** [comment]
This means that your host/server running this is running out of memory. Here's a [reference](https://laracasts.com/discuss/channels/laravel/the-process-has-been-signaled-with-signal-9) to understand why this is happening.
